### ISSUE TITLE
dynamic wp-config

### ISSUE THREAD

**Issue by celevra** [devgeniem/docker-alpine-wordpress#1]
HI,

thank you for this brilliant image!
i want to dynamicly configure worpress to connect to a database depending on witch host it runs.
I thought thats what the environment variables are for, but it isnt working, if i start the image with 
wp core download
and start it again i get the normal installer with /wp after the domain
if i put wordpress my self into /data/core/web i get also the installer.
So my question, what are the envs for btw what am i doing wrong?

regards

**Comment by onnimonni** [comment]
This is meant to be a runtime for your wordpress code but it doesn't include wordpress itself. You can see our wp project template [devgeniem/wp-project](https://github.com/devgeniem/wp-project) for more. If you are familiar with docker-compose.yml have a look at our example [docker-compose.yml](https://github.com/devgeniem/wp-project/blob/master/docker-compose.yml).

**Comment by celevra** [comment]
thanks for the fast answer.
yes its clear to me that i have to provide the wordpress files. But i though it would be possible to dynamicly reconfigure wordpress on every restart.
i'm on a 3 node coreos cluster and if one node goes down the container will be restarted on another node.
But than it needs so connect to an other mysql host as before (becauso the old one is also down).

it should be very simple to do a sed search and replace on these fields. Would it be ok for you if i code it on my own and open a pull request?

**Comment by onnimonni** [comment]
Thanks for the idea for the contribution but sorry, I wouldn't accept that PR into this repo. That's not the design we have in here. Instead of hard coded addresses you should get those envs dynamically from etcd or consul by using dns discovery. The dns can return different result after one of your coreos nodes goes down.

We don't use coreos but we use clustered environment where we use [consul](https://consul.io) to register domain `db.service.consul`. That domain is then given to container as `DB_HOST=db.service.consul` and consul makes sure that requests ends into healthy database. This way our developers don't have to create any logic for the clustering and they can just use `$DB_HOST` env and trust that it will work no matter where the container is running.

**Comment by onnimonni** [comment]
What you could do is to write a cronjob in your project and mount it in `/data/code/tasks.cron` and it could update contents of `/data/code/.env` which wordpress could use through `getenv()`.

See `.env` here: https://github.com/roots/bedrock/blob/master/config/application.php#L17-L21

And example `tasks.cron`: https://github.com/devgeniem/wp-project/blob/master/tasks.cron

**Comment by celevra** [comment]
Get env is exactly what I need. The env variable for DB Host is allready set on container start

So all I have todo is change the wp-config

Thank you very much for your help

---

Von: Onni Hakala notifications@github.com
Gesendet: 11.05.2016 10:27 nachm.
An: devgeniem/docker-alpine-wordpress
Cc: Philipp Zeitschel; Author
Betreff: Re: [devgeniem/docker-alpine-wordpress] dynamic wp-config (#1) 

What you could do is to write a cronjob in your project and mount it in /data/code/tasks.cron and it could update contents /data/code/.env which wordpress then uses through getenv().

See .env here: https://github.com/roots/bedrock/blob/master/config/application.php#L17-L21

And example tasks.cron: https://github.com/devgeniem/wp-project/blob/master/tasks.cron

**Comment by onnimonni** [comment]
You're welcome!

As you can see in our [application.php](https://github.com/devgeniem/wp-project/blob/master/config/application.php) we use quite a lot `env()` from `oscarotero/env` which handles env type conversions like `string "12"` -> `int 12` better than `getenv()`.

I want to remind you to use tagged versions of this image since the :latest tag can still move quite fast for this project because this is in active development. I try not to break things but you never know :).

I close this for now, happy coding!
